/**
 * Turns the raw camera photos in assets/originals/ into web-sized WebP served
 * from public/images/, and writes src/data/images.ts so the app knows the
 * available widths and intrinsic sizes (needed for srcset and to avoid layout
 * shift).
 *
 * Runs automatically before `npm run dev` and `npm run build`. Outputs are
 * skipped when they're newer than their source, so repeat runs are cheap.
 */
import { mkdir, readdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = path.resolve(import.meta.dirname, '..');
const SRC = path.join(ROOT, 'assets/originals');
const OUT = path.join(ROOT, 'public/images');
const MANIFEST = path.join(ROOT, 'src/data/images.ts');

// The hero sits behind a blur and a dark gradient, so it survives heavy
// compression. The gallery is viewed directly, so it gets a higher quality.
const PRESETS = {
  hero: { widths: [768, 1280, 1920], quality: 66 },
  gallery: { widths: [400, 800], quality: 76, square: true },
};

// The hero carousel plays in this order; anything else in the folder is ignored.
const HERO_ORDER = [
  'performance-1',
  'crowd-1',
  'performance-2',
  'crowd-2',
  'performance-3',
];

const OG_SOURCE = 'hero/performance-1';
const IMAGE_RE = /\.(jpe?g|png|webp)$/i;

const isStale = async (src, out) => {
  try {
    const [a, b] = await Promise.all([stat(src), stat(out)]);
    return a.mtimeMs > b.mtimeMs;
  } catch {
    return true; // output missing
  }
};

async function processDir(kind) {
  const { widths, quality, square } = PRESETS[kind];
  const outDir = path.join(OUT, kind);
  await mkdir(outDir, { recursive: true });

  const files = (await readdir(path.join(SRC, kind))).filter((f) => IMAGE_RE.test(f));
  const entries = [];

  for (const file of files) {
    const name = file.replace(IMAGE_RE, '');
    const srcPath = path.join(SRC, kind, file);
    const meta = await sharp(srcPath).metadata();

    // Never upscale: a 900px-wide source shouldn't be stretched to 1920.
    const targets = widths.filter((w) => w <= meta.width);
    if (targets.length === 0) targets.push(meta.width);

    for (const width of targets) {
      const outPath = path.join(outDir, `${name}-${width}.webp`);
      if (!(await isStale(srcPath, outPath))) continue;

      const pipeline = sharp(srcPath).rotate(); // honour EXIF orientation
      if (square) {
        pipeline.resize(width, width, { fit: 'cover', position: 'attention' });
      } else {
        pipeline.resize({ width, withoutEnlargement: true });
      }
      await pipeline.webp({ quality }).toFile(outPath);
      console.log(`  ${kind}/${name}-${width}.webp`);
    }

    const largest = targets[targets.length - 1];
    entries.push({
      name,
      widths: targets,
      // Intrinsic size of the largest rendition, so the browser can reserve space.
      width: square ? largest : largest,
      height: square ? largest : Math.round((meta.height / meta.width) * largest),
    });
  }

  return entries;
}

async function buildOgImage() {
  const [kind, name] = OG_SOURCE.split('/');
  const files = await readdir(path.join(SRC, kind));
  const file = files.find((f) => f.replace(IMAGE_RE, '') === name);
  if (!file) {
    console.warn(`  ! og:image source ${OG_SOURCE} not found, skipping`);
    return;
  }
  const outPath = path.join(OUT, 'og-image.jpg');
  const srcPath = path.join(SRC, kind, file);
  if (!(await isStale(srcPath, outPath))) return;

  // Facebook/WhatsApp/X all want a 1200x630 JPEG; WebP cards render unreliably.
  await sharp(srcPath)
    .rotate()
    .resize(1200, 630, { fit: 'cover', position: 'attention' })
    .jpeg({ quality: 82, mozjpeg: true })
    .toFile(outPath);
  console.log('  og-image.jpg');
}

const sortHero = (entries) =>
  entries
    .filter((e) => HERO_ORDER.includes(e.name))
    .sort((a, b) => HERO_ORDER.indexOf(a.name) - HERO_ORDER.indexOf(b.name));

console.log('Optimizing images...');
const hero = sortHero(await processDir('hero'));
const gallery = await processDir('gallery');
await buildOgImage();

const manifest = `// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export interface ImageAsset {
  /** Base filename, e.g. "performance-1". */
  name: string;
  /** Rendition widths available as /images/<kind>/<name>-<width>.webp */
  widths: number[];
  /** Intrinsic size of the largest rendition, used to reserve layout space. */
  width: number;
  height: number;
}

export const heroImages: ImageAsset[] = ${JSON.stringify(hero, null, 2)};

export const galleryImages: ImageAsset[] = ${JSON.stringify(gallery, null, 2)};

export const srcSet = (kind: 'hero' | 'gallery', image: ImageAsset): string =>
  image.widths.map((w) => \`/images/\${kind}/\${image.name}-\${w}.webp \${w}w\`).join(', ');

export const fallbackSrc = (kind: 'hero' | 'gallery', image: ImageAsset): string =>
  \`/images/\${kind}/\${image.name}-\${image.widths[image.widths.length - 1]}.webp\`;
`;

await mkdir(path.dirname(MANIFEST), { recursive: true });
await writeFile(MANIFEST, manifest);
console.log(`Done. ${hero.length} hero, ${gallery.length} gallery.`);
