// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export interface ImageAsset {
  /** Base filename, e.g. "performance-1". */
  name: string;
  /** Rendition widths available as /images/<kind>/<name>-<width>.webp */
  widths: number[];
  /** Intrinsic size of the largest rendition, used to reserve layout space. */
  width: number;
  height: number;
}

export const heroImages: ImageAsset[] = [
  {
    "name": "performance-1",
    "widths": [
      768
    ],
    "width": 768,
    "height": 1024
  },
  {
    "name": "crowd-1",
    "widths": [
      768,
      1280
    ],
    "width": 1280,
    "height": 983
  },
  {
    "name": "performance-2",
    "widths": [
      692
    ],
    "width": 692,
    "height": 1092
  },
  {
    "name": "crowd-2",
    "widths": [
      768,
      1280,
      1920
    ],
    "width": 1920,
    "height": 1080
  },
  {
    "name": "performance-3",
    "widths": [
      768,
      1280,
      1920
    ],
    "width": 1920,
    "height": 1280
  }
];

export const galleryImages: ImageAsset[] = [
  {
    "name": "IMG_0571",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_0585",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_0698",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_0835",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_4069",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_4381",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_4391",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_4398",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_4420",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_4438",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "IMG_6027",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "c415eca0-2884-4818-b6bc-662ada0eab9f",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "cf004465-439f-46ff-a57c-0c82977e29da",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "crowd-1",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "halloween2025_1",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "halloween2025_2",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  },
  {
    "name": "performance-3",
    "widths": [
      400,
      800
    ],
    "width": 800,
    "height": 800
  }
];

export const srcSet = (kind: 'hero' | 'gallery', image: ImageAsset): string =>
  image.widths.map((w) => `/images/${kind}/${image.name}-${w}.webp ${w}w`).join(', ');

export const fallbackSrc = (kind: 'hero' | 'gallery', image: ImageAsset): string =>
  `/images/${kind}/${image.name}-${image.widths[image.widths.length - 1]}.webp`;
